# Generated by Django 4.1.2 on 2022-10-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField()),
                ('title', models.CharField(max_length=254, unique=True)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='about_img')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='about_img')),
                ('price', models.CharField(max_length=254, unique=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_price', to='services.servicespages')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='about_img')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_box', to='services.servicespages')),
            ],
        ),
    ]
