# Generated by Django 4.1.2 on 2022-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespages',
            name='texttwo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicespages',
            name='titletwo',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='servicespages',
            name='title',
            field=models.CharField(max_length=254),
        ),
    ]
