# Generated by Django 4.1.2 on 2022-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicespages_texttwo_servicespages_titletwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesprice',
            name='subtitle',
            field=models.CharField(default='', max_length=254),
        ),
    ]
