# Generated by Django 4.1.2 on 2022-10-27 14:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('img', models.FileField(upload_to='about_img')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='logo_img')),
                ('title', models.CharField(blank=True, max_length=254, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hone', models.CharField(max_length=254, unique=True)),
                ('htwo', models.TextField(default='0')),
                ('caurosel', models.CharField(blank=True, choices=[('active', 'active'), ('', 'not active')], default='not active', max_length=254)),
                ('img', models.ImageField(blank=True, upload_to='carousel_img')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_button', to='services.servicespages')),
            ],
        ),
    ]
