# Generated by Django 4.1.2 on 2022-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='caurosel',
            field=models.CharField(choices=[('active', 'active'), ('notactive', 'notactive')], default='notactive', max_length=254),
        ),
    ]
