# Generated by Django 4.1.2 on 2022-10-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesprice_subtitle'),
        ('main', '0002_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hone', models.CharField(max_length=254, unique=True)),
                ('htwo', models.TextField(default='0')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_button', to='services.servicespages')),
            ],
        ),
    ]
