# Generated by Django 4.1.2 on 2022-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hero_caurosel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='caurosel',
            field=models.CharField(choices=[('active', 'active'), ('', '')], default='', max_length=254),
        ),
    ]
