# Generated by Django 4.1.2 on 2022-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(blank=True, upload_to='carousel_img'),
        ),
    ]
