# Generated by Django 4.1.2 on 2022-10-23 16:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hero_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
