# Generated by Django 4.1.2 on 2022-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('still in development', 'still in development'), ('on air', 'on air'), ('cancelled', 'cancelled')], default='still in development', max_length=254)),
                ('img', models.FileField(blank=True, upload_to='examples')),
                ('url_to_website', models.URLField()),
            ],
        ),
    ]
