# Generated by Django 4.1.2 on 2022-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumary',
            name='textthree',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
